'use client';import{useState}from'react';
const wa='https://wa.me/5594981556350',insta='https://www.instagram.com/hospitalamordepatas.pa/',map='https://www.google.com/maps/search/?api=1&query=Hospital+Amor+de+Patas+Parauapebas';
const services=[['Hospital 24h','Atendimento veterinário e suporte para quando seu pet mais precisa.','/hospital.jpg'],['Vacinas','Prevenção e proteção para cães e gatos em todas as fases.','/vacina.jpg'],['Exames','Apoio diagnóstico para um cuidado mais preciso e seguro.','/exames.jpg'],['Banho & tosa','Bem-estar, higiene e carinho em cada detalhe.','/banho.jpg'],['Pet shop','Rações e produtos escolhidos para a rotina do seu melhor amigo.','/shop.jpg']];
export default function Home(){const[menu,setMenu]=useState(false),[active,setActive]=useState(0);return <main>
<header><a className="logo" href="#inicio"><img src="/logo.jpg" alt="Amor de Patas"/><small>HOSPITAL & PET SHOP</small></a><nav id="mobileNav" className={menu?'open':''}><a href="#cuidado">Cuidado</a><a href="#servicos">Serviços</a><a href="#estrutura">Estrutura</a><a href="#contato">Contato</a></nav><a className="headCta" href={wa}>PLANTÃO 24H ↗</a><button aria-expanded={menu} aria-controls="mobileNav" onClick={()=>setMenu(!menu)}>{menu?'FECHAR':'MENU'}</button></header>
<section className="hero" id="inicio"><div className="heroDecor" aria-hidden="true"><span className="deco paw p1">🐾</span><span className="deco paw p2">🐾</span><span className="deco paw p3">🐾</span><span className="deco paw p4">🐾</span><span className="deco circle c1"></span><span className="deco circle c2"></span><span className="deco circle c3"></span><span className="deco star s1">✦</span><span className="deco star s2">✦</span><span className="deco star s3">✦</span></div><div className="heroText" data-r><p className="tag">HOSPITAL VETERINÁRIO • PARAUAPEBAS</p><h1>Amor que<br/><em>cuida.</em></h1><p>Saúde, proteção e bem-estar para quem faz parte da sua família — a qualquer hora.</p><a className="cta" href={wa}>FALAR COM O PLANTÃO <span>↗</span></a></div><div className="collage" data-r><div className="blob main"><img src="/hero.jpg" alt="Cão recebendo carinho"/></div><div className="blob small"><img src="/gato.jpg" alt="Gato saudável"/></div><span className="heart">♥</span><p>ABERTO<br/><strong>24H</strong></p></div><div className="scribble">cuidado de verdade</div></section>
<section className="ticker"><div>PLANTÃO 24 HORAS ✦ HOSPITAL VETERINÁRIO ✦ PET SHOP ✦ BANHO & TOSA ✦ VACINAS ✦ EXAMES ✦ PLANTÃO 24 HORAS ✦</div></section>
<section className="care" id="cuidado"><aside data-r><span>01 / NOSSO JEITO</span><h2>Todo pet merece ser cuidado como <em>único.</em></h2></aside><div className="carePic" data-r><img src="/carinho.jpg" alt="Veterinária cuidando de um cachorro" loading="lazy" decoding="async"/><i>🐾</i></div><div className="careCopy" data-r><p>Acolher o tutor. Respeitar cada animal. Unir atenção, estrutura e presença para cuidar em todos os momentos.</p><strong>Hospital + prevenção + bem-estar<br/>em um só lugar.</strong></div></section>
<section className="services" id="servicos"><div className="serviceImage"><img src={services[active][2]} alt={services[active][0]} loading="lazy" decoding="async"/></div><div className="serviceList"><p>02 / TUDO PARA SEU PET</p><h2>Do urgente<br/>ao cotidiano.</h2>{services.map((s,i)=><button aria-pressed={active===i} className={active===i?'active':''} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>setActive(i)} key={s[0]}><span>0{i+1}</span><b>{s[0]}</b><em>{s[1]}</em><i>↗</i></button>)}</div></section>
<section className="promise"><p data-r>Quando eles não conseguem dizer onde dói,</p><h2 data-r>a gente observa.<br/><em>escuta. cuida.</em></h2><div className="orbit">24<span>H</span></div></section>
<section className="gallery" id="estrutura"><div className="galleryHead"><span>03 / POR DENTRO</span><h2>Um espaço feito<br/>para receber bem.</h2></div><div className="film"><figure><img src="/galeria1.jpg" alt="Cão no atendimento" loading="lazy" decoding="async"/><figcaption>ATENDIMENTO</figcaption></figure><figure className="tall"><img src="/galeria2.jpg" alt="Gato no veterinário" loading="lazy" decoding="async"/><figcaption>ACOLHIMENTO</figcaption></figure><figure><img src="/galeria3.jpg" alt="Pet shop" loading="lazy" decoding="async"/><figcaption>BEM-ESTAR</figcaption></figure></div></section>
<section className="contact" id="contato"><div className="contactTitle" data-r><span>04 / ESTAMOS AQUI</span><h2>Seu pet precisa<br/>de cuidado <em>agora?</em></h2></div><a className="bigWa" href={wa}>CHAMAR NO WHATSAPP <b>↗</b></a><div className="info"><div><small>ENDEREÇO</small><p>Av. dos Ipês, Qd. 46, Lt. 21<br/>Cidade Jardim · Parauapebas — PA</p><a href={map}>ABRIR NO MAPA ↗</a></div><div><small>ATENDIMENTO</small><p>Hospital e Pet Shop<br/><strong>24 horas, todos os dias.</strong></p></div><div><small>CONTATO</small><p>(94) 98155-6350</p><a href={insta}>@hospitalamordepatas.pa ↗</a></div></div><div className="footLogo">AMOR<span>♥</span>PATAS</div><footer>© 2026 AMOR DE PATAS <a href="#inicio">VOLTAR AO TOPO ↑</a></footer></section>
<a className="float" href={wa}>♥ <span>PLANTÃO 24H</span></a></main>}
